name: run-codeguru-reviewer
author: ytdh7834@gmail.com
description: Code Guru Reviewer (https://github.com/marketplace/actions/codeguru-reviewer)

inputs:
  s3_bucket:
    description: S3 bucket where your code is uploaded
runs:
  using: composite
  steps:
    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        s3_bucket: ${{ inputs.s3_bucket }}
    - name: Store SARIF file
      uses: actions/upload-artifact@v2
      with:
        name: SARIF_recommendation
        path: ./codeguru-results.sarif.json
    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: codeguru-results.sarif.json
